blog_post/auth.py
from flask import Blueprint, redirect, url_for, render_template, flash, request
from .forms import RegistrationForm, LoginForm, RequestResetForm, ResetPasswordForm
from .models import User, Post
from . import db, mail
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, current_user, login_required
from flask_mail import Message

auth = Blueprint("auth", __name__)


@auth.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("views.home"))

    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        
        if user:
            if check_password_hash(user.password, form.password.data):
                login_user(user, remember=form.remember.data)
                next_page = request.args.get("next")
                flash("You have been logged in!", category="success")
                return redirect(next_page) if next_page else redirect(url_for("views.home"))
            else:
                flash("Password is incorrect.", category="danger")
        else:
            flash("Email is not registered.", category="danger")

    return render_template("login.html", form=form)


@auth.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("views.home"))

    form = RegistrationForm()

    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data, method="sha256")
        new_user = User(email=form.email.data, username=form.username.data, password=hashed_password)
        db.session.add(new_user)
        db.session.commit()
        login_user(new_user)

        flash(f"Account created for {form.username.data}!", category="success")
        return redirect(url_for("views.home"))
        
    return render_template("register.html", form=form)


@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("views.home"))


def send_reset_email(user):
    token = user.get_reset_token()
    message = Message("Pasword Reset Request", sender="noreply@demo.com", recipients=[user.email])
    message.body = f'''To reset the password, visit the following link:
{url_for("auth.reset_password", token=token, _external=True)}

If you did not make this request, then simply ignore this email and no changes will be made.
    '''
    mail.send(message)


@auth.route("/reset-password", methods=["GET", "POST"])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for("views.home"))

    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)

        flash("An email has been sent with instructions to reset your password", category="info")
        return redirect(url_for("auth.login"))

    return render_template("reset_request.html", form=form)


@auth.route("/reset-password/<token>", methods=["GET", "POST"])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for("views.home"))

    user = User.verify_reset_token(token)

    if not user:
        flash("This is an invalid or expired token", category="warning")
        return redirect(url_for("auth.reset_request"))

    form = ResetPasswordForm()
    if form.validate_on_submit():
        new_hashed_password = generate_password_hash(form.password.data, method="sha256")
        user.password = new_hashed_password
        db.session.commit()

        flash("You password has been updated. You are now able to log in", category="success")
        return redirect(url_for("auth.login"))

    return render_template("reset_password.html", form=form)

blog_post/views.py
from flask import Blueprint, render_template, url_for, request, flash, redirect, url_for, abort
from flask_login import login_required, current_user
from .forms import UpdateAccountForm, PostForm
from . import db
from .models import Post, User
from PIL import Image, ImageOps
from io import BytesIO

import secrets
import os

views = Blueprint("views", __name__)


@views.route("/")
@views.route("/home")
def home():
    page = request.args.get("page", 1, type=int);
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template("home.html", posts=posts)


@views.route("/about")
def about():
    return render_template("about.html")


def save_picture(picture):
    random_hex = secrets.token_hex(8);
    _, file_extension = os.path.splitext(picture.filename) 
    picture_name = random_hex + file_extension
    picture_path = os.path.join(views.root_path, "static/profile_pics", picture_name)
    
    output_size = (125, 125)
    image = Image.open(picture)
    resized_image = ImageOps.exif_transpose(image)
    # Need some testing here b/w 'Image.resize' and 'Image.thumnail'
    resized_image.resize(output_size)

    resized_image.save(picture_path)

    return picture_name


@views.route("/account", methods=["GET", "POST"])
@login_required
def account():
    form = UpdateAccountForm()

    if form.validate_on_submit():
        if form.picture.data:
            image_file = save_picture(form.picture.data)
            current_user.image_file = image_file

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()

        flash("You account has been updated!", category="success")
        return redirect(url_for("views.account"))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email

    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template("account.html", image_file=image_file, form=form)


@views.route("/post/new", methods=["GET", "POST"])
@login_required
def create_post():
    form = PostForm()

    if form.validate_on_submit():
        new_post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(new_post)
        db.session.commit()

        flash("Your post has been created!", category="success")
        return redirect(url_for("views.home"))

    return render_template("create_post.html", form=form, legend_title="New Post")


@views.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template("post.html", post=post)


@views.route("/post/<int:post_id>/update", methods=["GET", "POST"])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    form = PostForm()

    if post.author != current_user:
        abort(403)

    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()

        flash("Your post has been updated!", category="success")
        return redirect(url_for("views.post", post_id=post.id))
    elif request.method == "GET":
        form.title.data = post.title
        form.content.data = post.content

    return render_template("create_post.html", form=form, legend_title="Update Post")


@views.route("/delete-post/<int:post_id>", methods=["POST"])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)

    if post.author != current_user:
        abort(403)

    db.session.delete(post) 
    db.session.commit()

    flash("Your post has been deleted!", category="success")
    return redirect(url_for("views.home"))


@views.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get("page", 1, type=int);
    user = User.query.filter_by(username=username).first_or_404()

    posts = Post.query.filter_by(author=user)\
            .order_by(Post.date_posted.desc())\
            .paginate(page=page, per_page=5)

    return render_template("user_posts.html", posts=posts, user=user)

blog_post/templates/about.html
{% extends "base.html" %}

{% block title %}About{% endblock %}
{% block content %}
    <h1>About page</h1>
{% endblock %}

blog_post/templates/account.html
{% extends "base.html" %}

{% block title %}Account{% endblock %}
{% block content %}
    <div class="content-section">
        <div class="media d-flex">
            <img class="rounded-circle account-img" src="{{ image_file }}">
            <div class="media-body">
                <h2 class="account-heading">{{ current_user.username }}</h2>
                <p class="text-secondary">{{ current_user.email }}</p>
            </div>
        </div>

        <form method="POST" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom pb-2">Account Info</legend>
                <div class="form-group my-2">
                    {{ form.username.label(class="form-control-label my-1") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group my-2">
                    {{ form.email.label(class="form-control-label my-1") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group my-3">
                    {{ form.picture.label(class="my-1") }}
                    <br />
                    {{ form.picture(class="form-control-file my-1") }}

                    {% if form.picture.errors %}
                        <div class="text-danger">
                            {% for error in form.picture.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group my-2">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock %}

blog_post/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <!-- Bootstrap stylesheet -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
            crossorigin="anonymous"
        />

        <!-- Local css stylesheet -->
        <link
            rel="stylesheet"
            type="text/css"
            href="{{ url_for('static', filename='main.css') }}"
        />

        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <!-- Navbar section -->
        <header class="site-header">
            <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
                <div class="container">
                    <a class="navbar-brand mr-4" href="{{ url_for('views.home') }}">BlogPost</a>
                    <button
                        class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarToggle"
                        aria-controls="navbarToggle"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                    >
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarToggle">
                        <div class="navbar-nav">
                            <a class="nav-item nav-link" href="{{ url_for('views.home') }}">Home</a>
                            <a class="nav-item nav-link" href="{{ url_for('views.about') }}">About</a>
                        </div>
                        <!-- Navbar Right Side -->
                        <div class="navbar-nav ms-auto">
                            {% if current_user.is_authenticated %}
                                <a class="nav-item nav-link" href="{{ url_for('views.create_post') }}">New Post</a>
                                <a class="nav-item nav-link" href="{{ url_for('views.account') }}">Account</a>
                                <a class="nav-item nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                            {% else %}
                                <a class="nav-item nav-link" href="{{ url_for('auth.login') }}">Login</a>
                                <a class="nav-item nav-link" href="{{ url_for('auth.register') }}">Register</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </header>

        <!-- Main section -->
        <main role="main" class="container">
            <div class="row">
                <div class="col-md-8">
                    {% with messages = get_flashed_messages(with_categories=true) %}
                        {% if messages %}
                            {% for category, message in messages %}
                                <div class="alert alert-{{ category }}">
                                    {{ message }}     
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}
                    {% block content %}{% endblock %}
                </div>
                <div class="col-md-4">
                    <div class="content-section">
                        <h3>Our Sidebar</h3>
                        <p class='text-muted'>You can put any information here you'd like.
                            <ul class="list-group">
                                <li class="list-group-item list-group-item-light">Latest Posts</li>
                                <li class="list-group-item list-group-item-light">Announcements</li>
                                <li class="list-group-item list-group-item-light">Calendars</li>
                                <li class="list-group-item list-group-item-light">etc</li>
                            </ul>
                        </p>
                    </div>
                </div>
            </div>
        </main>

        <!-- Bootstrap script -->
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
            crossorigin="anonymous"
        ></script>
    </body>
</html>

blog_post/templates/create_post.html
{% extends "base.html" %}

{% block title %}{{ legend_title }}{% endblock %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom pb-2">{{ legend_title }}</legend>
                <div class="form-group my-2">
                    {{ form.title.label(class="form-control-label my-1") }}

                    {% if form.title.errors %}
                        {{ form.title(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group my-2">
                    {{ form.content.label(class="form-control-label my-1") }}

                    {% if form.content.errors %}
                        {{ form.content(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.content(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group my-2">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock %}

blog_post/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}
{% block content %}
    {% for post in posts.items %}
        <article class="media content-section d-flex">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename="profile_pics/" + post.author.image_file) }}"></img>
            <div class="media-body">
                <div class="article-metadata">
                    <a class="text-decoration-none" href="{{ url_for('views.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                    <small class="text-muted mx-1">{{ post.date_posted.strftime("%d-%m-%Y") }}</small>
                </div>
                <h2><a class="article-title" href="{{ url_for('views.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}

    {% for page in posts.iter_pages(left_edge=1, right_edge=2, left_current=1, right_current=2) %}
        {% if page %}
            {% if posts.page == page %} 
                <a class="btn btn-info btn-sm mb-4" href="{{ url_for('views.home', page=page) }}">{{ page }}</a>
            {% else %}
                <a class="btn btn-outline-info btn-sm mb-4" href="{{ url_for('views.home', page=page) }}">{{ page }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock %}

blog_post/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom pb-2">Log In</legend>
                <div class="form-group my-2">
                    {{ form.email.label(class="form-control-label my-1") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group my-2">
                    {{ form.password.label(class="form-control-label my-1") }}

                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check my-2 mt-3">
                    {{ form.remember.label(class="form-check-label") }} 
                    {{ form.remember(class="form-check-input") }}
                </div>
            </fieldset>
            <div class="form-group my-2">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted">
                <a href="{{ url_for("auth.reset_request") }}">Forgot Password?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need an account? <a href="{{ url_for('auth.register') }}" class="ml-2">Sign Up Now</a>
        </small>
    </div>
{% endblock %}

blog_post/templates/post.html
{% extends "base.html" %}

{% block title %}Post{% endblock %}
{% block content %}
    <article class="media content-section d-flex">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename="profile_pics/" + post.author.image_file) }}"></img>
        <div class="media-body">
            <div class="article-metadata">
                <a class="text-decoration-none" href="{{ url_for('views.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                <small class="text-muted mx-1">{{ post.date_posted.strftime("%d-%m-%Y") }}</small>
                {% if post.author == current_user %}
                    <a class="btn btn-secondary btn-sm my-1" href="{{ url_for('views.update_post', post_id=post.id) }}">Update</a>
                    <button type="button" class="btn btn-danger btn-sm m-1" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>
                {% endif %}
            </div>
            <h2 class="article-title">{{ post.title }}</h2>
            <p class="article-content">{{ post.content }}</p>
        </div>
    </article>

    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <form action="{{ url_for('views.delete_post', post_id=post.id) }}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete" />
            </form> 
          </div>
        </div>
      </div>
    </div>
{% endblock %}

blog_post/templates/register.html
{% extends "base.html" %}

{% block title %}Register{% endblock %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom pb-2">Join Today</legend>
                <div class="form-group my-2">
                    {{ form.username.label(class="form-control-label my-1") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group my-2">
                    {{ form.email.label(class="form-control-label my-1") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group my-2">
                    {{ form.password.label(class="form-control-label my-1") }}

                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group my-2">
                    {{ form.confirm_password.label(class="form-control-label my-1") }}

                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group my-2">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already have an account? <a href="{{ url_for('auth.login') }}" class="ml-2">Sign In</a>
        </small>
    </div>
{% endblock %}

blog_post/templates/reset_password.html
{% extends "base.html" %}

{% block title %}Reset Password{% endblock %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom pb-2">Reset Password</legend>
                <div class="form-group my-2">
                    {{ form.password.label(class="form-control-label my-1") }}

                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group my-2">
                    {{ form.confirm_password.label(class="form-control-label my-1") }}

                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group my-2">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock %}

blog_post/templates/reset_request.html
{% extends "base.html" %}

{% block title %}Reset Password{% endblock %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom pb-2">Reset Password</legend>
                <div class="form-group my-2">
                    {{ form.email.label(class="form-control-label my-1") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group my-2">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock %}

blog_post/templates/user_posts.html
{% extends "base.html" %}

{% block title %}{{ user.username }} Posts{% endblock %}
{% block content %}
    <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
        <article class="media content-section d-flex">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename="profile_pics/" + post.author.image_file) }}"></img>
            <div class="media-body">
                <div class="article-metadata">
                    <a class="text-decoration-none" href="{{ url_for('views.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                    <small class="text-muted mx-1">{{ post.date_posted.strftime("%d-%m-%Y") }}</small>
                </div>
                <h2><a class="article-title" href="{{ url_for('views.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}

    {% for page in posts.iter_pages(left_edge=1, right_edge=2, left_current=1, right_current=2) %}
        {% if page %}
            {% if posts.page == page %} 
                <a class="btn btn-info btn-sm mb-4" href="{{ url_for('views.user_posts', page=page, username=user.username) }}">{{ page }}</a>
            {% else %}
                <a class="btn btn-outline-info btn-sm mb-4" href="{{ url_for('views.user_posts', page=page, username=user.username) }}">{{ page }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock %}